const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('overlay', {
  onConfig: (callback) => ipcRenderer.on('config', (_event, value) => callback(value)),
  onInput: (callback) => ipcRenderer.on('input', (_event, value) => callback(value)),
  onStatus: (callback) => ipcRenderer.on('input-status', (_event, value) => callback(value)),
  onSkin: (callback) => ipcRenderer.on('skin', (_event, value) => callback(value)),
  onClickThrough: (callback) => ipcRenderer.on('click-through', (_event, value) => callback(value)),
  onMoveMode: (callback) => ipcRenderer.on('move-mode', (_event, value) => callback(value)),
  onLighting: (callback) => ipcRenderer.on('lighting', (_event, value) => callback(value)),
  onStreamMode: (callback) => ipcRenderer.on('stream-mode', (_event, value) => callback(value)),
  onLayout: (callback) => ipcRenderer.on('layout', (_event, value) => callback(value)),
  onOverlayState: (callback) => ipcRenderer.on('overlay-state', (_event, value) => callback(value)),
  onSettingsTab: (callback) => ipcRenderer.on('select-settings-tab', (_event, value) => callback(value)),
  localInput: (value) => ipcRenderer.send('local-input', value),
  toggleClickThrough: () => ipcRenderer.send('toggle-click-through'),
  toggleMoveMode: () => ipcRenderer.send('toggle-move-mode'),
  toggleStreamMode: () => ipcRenderer.send('toggle-stream-mode'),
  toggleLayout: () => ipcRenderer.send('toggle-layout'),
  openSettings: (tab = 'general') => ipcRenderer.send('open-settings', tab),
  adjustWindowSize: (direction) => ipcRenderer.send('adjust-window-size', direction),
  setInteractiveHover: (interactive) => ipcRenderer.send('interactive-hover', interactive),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  updateSettings: (patch) => ipcRenderer.invoke('update-settings', patch),
  setHotkeys: (hotkeys) => ipcRenderer.invoke('set-hotkeys', hotkeys),
  listProfiles: () => ipcRenderer.invoke('list-profiles'),
  chooseProfilesDirectory: () => ipcRenderer.invoke('choose-profiles-directory'),
  saveProfile: (name) => ipcRenderer.invoke('save-profile', name),
  loadProfile: (name) => ipcRenderer.invoke('load-profile', name),
  deleteProfile: (name) => ipcRenderer.invoke('delete-profile', name),
  setMapping: (button, code) => ipcRenderer.invoke('set-mapping', { button, code }),
  setLighting: (lighting) => ipcRenderer.invoke('set-lighting', lighting)
});
